### ISSUE TITLE
Notebook 4 pre trained QNN model cannot be downloaded

### ISSUE THREAD

**Issue by sanchit-ahuja** [maltanar/qnn-inference-examples#3]
The url is dead for downloading the model. Any other place where we can download the model from?

**Comment by maltanar** [comment]
Thanks for pointing this out. I still had a copy lying around, which I uploaded here:

https://zenodo.org/record/3771242#.XqdSGIBKgaw

**Comment by sanchit-ahuja** [comment]
Thanks!
